// reactjs/src/components/hand-image.js
import { useTranslation } from "react-i18next";
import { Hand } from '../game/hand';
import './hand-image.scss';

export default function HandImage({ hand, isPlayer }) {
    const { t } = useTranslation();

    const isClickable = !isPlayer
    const cssClass = isClickable ? 'clickable' : 'choosen'
    const hideImage = () => !hand

    const label = () => {
        if (!hand) { return '' }

        if (!isClickable) { return hand.toString() }

        switch (hand) {
            case Hand.Rock:
                return "rock (press '1')"
            case Hand.Paper:
                return "paper (press '2')"
            case Hand.Scissors:
                return "scissors (press '3')"
            default:
                return ''
        }
    }

    const source = () => {
        switch (hand ?? '') {
            case Hand.Rock: return '/rock.svg?url'
            case Hand.Paper: return '/paper.svg?url'
            case Hand.Scissors: return '/scissors.svg?url'
            // need to return a value so :hidden takes space.
            default: return '/scissors.svg?url'
        }
    }

    return (
        <img className={cssClass} style={hideImage() ? { 'visibility': 'hidden' } : undefined} src={source()}
            alt={label() ? t(label()) : undefined} title={label() ? t(label()) : undefined} />
    )
}

// angular/src/app/components/hand-image/hand-image.component.ts
import { Component, Input, OnInit, Signal, computed, signal } from '@angular/core';
import { Hand } from '../../game/hand';
import { marker as _ } from '@biesbjerg/ngx-translate-extract-marker';
import { TranslateModule } from '@ngx-translate/core';

@Component({
  selector: 'app-hand-image',
  standalone: true,
  imports: [
    TranslateModule
  ],
  templateUrl: './hand-image.component.html',
  styleUrl: './hand-image.component.scss'
})
export class HandImageComponent implements OnInit {
  @Input({ required: true }) public hand!: Signal<Hand | undefined>
  @Input({ required: true }) public isPlayer!: boolean

  private readonly isClickable = signal(false)
  public readonly cssClass: Signal<string>
  public readonly hideImage: Signal<boolean>
  public readonly label: Signal<string>
  public readonly source: Signal<string>

  constructor() {
    this.cssClass = computed(() => this.isClickable() ? 'clickable' : 'choosen')
    this.hideImage = computed(() => !this.hand())

    this.label = computed(() => {
      const hand = this.hand()

      if (!hand) { return '' }

      if (!this.isClickable()) { return hand.toString() }

      switch (hand) {
        case Hand.Rock:
          return "rock (press '1')"
        case Hand.Paper:
          return "paper (press '2')"
        case Hand.Scissors:
          return "scissors (press '3')"
        default:
          return ''
      }
    })

    this.source = computed(() => {
      switch (this.hand() ?? '') {
        case Hand.Rock: return '/assets/rock.svg'
        case Hand.Paper: return '/assets/paper.svg'
        case Hand.Scissors: return '/assets/scissors.svg'
        // need to return a value so :hidden takes space.
        default: return '/assets/scissors.svg'
      }
    })
  }

  ngOnInit(): void {
    // Know only on OnInit the initial value of the hand.
    this.isClickable.set(!this.isPlayer)
  }
}

<img [class]="cssClass()" [style]="hideImage() ? 'visibility:hidden' : undefined" [src]="source()"
    [alt]="label() | translate" [title]="label() | translate" />
