// angular/src/app/components/player-hand/player-hand.component.ts
import { Component, Input, Signal, computed } from '@angular/core';
import { Player } from '../../game/player';
import { HandImageComponent } from '../hand-image/hand-image.component';

@Component({
  selector: 'app-player-hand',
  standalone: true,
  imports: [
    HandImageComponent
  ],
  templateUrl: './player-hand.component.html',
  styleUrl: './player-hand.component.scss'
})
export class PlayerHandComponent {
  @Input({ required: true }) public player!: Player

  public readonly cssClass: Signal<string | undefined>

  constructor() {
    this.cssClass = computed(() => {
      const wonLastGame = this.player.wonLastGame()
      const lostLastGame = this.player.lostLastGame()
      return wonLastGame ? 'winner'
        : lostLastGame ? 'loser'
          : 'tie'
    })
  }
}

<div class="player">
    <div [class]="cssClass()">
        <app-hand-image [hand]="player.hand" />
    </div>
    <p class="score">{{ player.percentage() }}</p>
</div>

// reactjs/src/components/player-hand.js
import './player-hand.scss';
import HandImage from "./hand-image"

export default function PlayerHand({ player }) {
    const cssClass = () => {
        const wonLastGame = player.wonLastGame
        const lostLastGame = player.lostLastGame
        return wonLastGame ? 'winner'
            : lostLastGame ? 'loser'
                : 'tie'
    }

    return (
        <div className="player">
            <div className={cssClass()}>
                <HandImage hand={player.hand} isPlayer={true} />
            </div>
            <p className="score">{player.percentage()}</p>
        </div>
    )
}
