// vue/src/components/SelectLocale.vue
<script setup lang="ts">
const langs = [
    { locale: 'en', title: 'English' },
    { locale: 'de', title: 'Deutsch' },
    { locale: 'fr', title: 'Français' }
]

const onChange = (locale: string) => {
    window.localStorage.setItem('language', locale)
}
</script>

<style lang="scss">
select {
    display: block;
    font-size: 1.5em;
    height: 2em;

    @media (prefers-color-scheme:dark) {
        color: #fff;
        background-color: #000;
    }
}
</style>

<template>
    <div class="locale-changer">
        <select v-model="$i18n.locale" :onchange="onChange($i18n.locale)">
            <option v-for="(lang, i) in langs" :key="`Lang${i}`" :value="lang.locale">
                {{ lang.title }}
            </option>
        </select>
    </div>
</template>

// reactjs/src/components/select-locale.js
import { useTranslation } from 'react-i18next';

import './select-locale.scss';
import { useEffect } from 'react';

export default function SelectLocale() {
    const { i18n } = useTranslation();

    const locale = window.localStorage.getItem('language')

    useEffect(() => {
        if (locale) { i18n.changeLanguage(locale) }
    },
        [i18n, locale])

    const langs = [
        { locale: 'en', title: 'English' },
        { locale: 'de', title: 'Deutsch' },
        { locale: 'fr', title: 'Français' }
    ]

    const options = langs.map(lang => (
        <option key={lang.locale} value={lang.locale}>
            {lang.title}
        </option>
    ))

    const onChange = function (element) {
        const locale = element?.target?.value
        i18n.changeLanguage(locale)
        window.localStorage.setItem('language', locale)
    }

    return (
        <div className="locale-changer">
            <select onChange={onChange} value={locale}>
                {options}
            </select>
        </div>
    )
}
