// angular/src/app/components/select-locale/select-locale.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-select-locale',
  standalone: true,
  imports: [],
  templateUrl: './select-locale.component.html',
  styleUrl: './select-locale.component.scss'
})
export class SelectLocaleComponent {
  public readonly langs = [
    { locale: 'en', title: 'English' },
    { locale: 'de', title: 'Deutsch' },
    { locale: 'fr', title: 'Français' }
  ]
}

<div class="locale-changer">
    <select>
        @for( lang of langs; track lang.locale ) {
        <option [value]="lang.locale">
            {{ lang.title }}
        </option>
        }
    </select>
</div>

// src/components/SelectLocale.vue
<script setup lang="ts">
</script>

<template>
    <div class="locale-changer">
        <select v-model="$i18n.locale">
            <option v-for="(lang, i) in langs" :key="`Lang${i}`" :value="lang.locale">
                {{ lang.title }}
            </option>
        </select>
    </div>
</template>
  
<script lang="js">

export default {
    name: 'locale-changer',
    data() {
        return { langs: [
            {locale:'en', title:'English'},
             {locale:'de', title:'Deutsch'},
             {locale: 'fr', title:'Français'}
            ] }
    }
}
</script>
