// angular/src/app/routes/about/about.component.ts
import { Component } from '@angular/core';
import { TranslateModule } from '@ngx-translate/core';
import { marker as _ } from '@biesbjerg/ngx-translate-extract-marker';
import { SelectLocaleComponent } from '../../components/select-locale/select-locale.component';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-about',
  standalone: true,
  imports: [
    TranslateModule,
    SelectLocaleComponent,
    RouterModule
  ],
  templateUrl: './about.component.html',
  styleUrl: './about.component.scss'
})
export class AboutComponent {
  public readonly title = _('Rock, paper, scissors');

}

<div class="content">
    <header>
        <h1>{{ title | translate }}</h1>

        <app-select-locale />
    </header>

    <p>{{'A rock-paper-scissors game against a computer opponent.' | translate}}</p>

    <a [routerLink]="'/play'" class="start-game">{{'Play!' | translate}}</a>

    <div class="alternatives">
        <h2>{{ 'Alternative frontend frameworks' | translate }}</h2>

        <p>{{ 'Why alternative frameworks.'| translate }}</p>

        <ol>
            <li><a href="../blazor/">Blazor</a></li>
            <li><a href="../react/">React.js</a></li>
            <li><a href="../vue/">Vue.js</a></li>
        </ol>
    </div>

    <div class="sources">
        <h2>{{'References' | translate}}</h2>

        <ol>
            <li><a href="https://github.com/elsehow/aaronson-oracle">{{
                    'Concept' | translate}}</a>
                ({{'Thanks to' | translate}}
                <a href="https://www.linkedin.com/in/harald-meyer-auf-m-hofe-00934a116/">Harald</a>
                {{'for the suggestion.' | translate}})
            </li>
            <li><a href="https://openclipart.org/detail/325645/hands-3">{{
                    'Source of the hand images.' | translate }}</a>
            </li>
            <li><a href="https://github.com/Daniel-Methfessel/rock-paper-scissors/tree/master/angular">{{
                    'GitHub repository for the source code of this page.' | translate}}</a></li>
            <li><a [href]="'http://www.DaMe-Software.' + ('com' | translate)">{{
                    'My website.' | translate }}</a></li>
        </ol>
    </div>
</div>

// reactjs/src/routes/about.js
import { useTranslation } from 'react-i18next';
import SelectLocale from '../components/select-locale';

import './about.scss';

export default function About() {
    const { t } = useTranslation();

    return (
        <div className="about-content">
            <header>
                <h1>{t('Rock, paper, scissors')}</h1>

                <SelectLocale />
            </header>

            <p>{t('A rock-paper-scissors game against a computer opponent.')}</p>

            <a href="/play" className="start-game">{t('Play!')}</a>

            <div className="alternatives">
                <h2>{t('Alternative frontend frameworks')}</h2>

                <p>{t('Why alternative frameworks.')}</p>

                <ol>
                    <li><a href="https://blazor.rock-paper-scissors.dame-software.com/">Blazor.js</a></li>
                    <li><a href="https://angular.rock-paper-scissors.dame-software.com/">Angular</a></li>
                    <li><a href="https://vue.rock-paper-scissors.dame-software.com/">Vue.js</a></li>
                </ol>
            </div>

            <div className="sources">
                <h2>{t('References')}</h2>

                <ol>
                    <li><a href="https://github.com/elsehow/aaronson-oracle">{
                        t('Concept')}</a>
                        &#xa0;
                        ({t('Thanks to')}
                        &#xa0;
                        <a href="https://www.linkedin.com/in/harald-meyer-auf-m-hofe-00934a116/">Harald</a>
                        &#xa0;
                        {t('for the suggestion.')})
                    </li>
                    <li><a href="https://openclipart.org/detail/325645/hands-3">{
                        t('Source of the hand images.')}</a></li>
                    <li><a href="https://github.com/Daniel-Methfessel/rock-paper-scissors/tree/master/reactjs">{
                        t('GitHub repository for the source code of this page.')}</a></li>
                    <li><a href={'http://www.DaMe-Software.' + t('com')}>{
                        t('My website.')}</a></li>
                </ol>
            </div>
        </div>
    )
}
