// angular/src/app/components/rock-paper-scissors/rock-paper-scissors.component.ts
import { Component, HostListener } from '@angular/core';
import { Game } from '../../game/game';
import { Hand } from '../../game/hand';
import { PlayerHandComponent } from '../player-hand/player-hand.component';
import { TheChoiceComponent } from '../the-choice/the-choice.component';

@Component({
  selector: 'app-rock-paper-scissors',
  standalone: true,
  imports: [
    PlayerHandComponent,
    TheChoiceComponent
  ],
  templateUrl: './rock-paper-scissors.component.html',
  styleUrl: './rock-paper-scissors.component.scss'
})
export class RockPaperScissorsComponent {
  public readonly gameState = new Game()

  constructor() {

  }

  @HostListener('document:keypress', ['$event'])
  handleKeyboardEvent(event: KeyboardEvent) {
    switch (event.key) {
      case '1':
        this.gameState.play(Hand.Rock)
        break
      case '2':
        this.gameState.play(Hand.Paper)
        break
      case '3':
        this.gameState.play(Hand.Scissors)
        break
    }
  }
}

// reactjs/src/routes/rock-paper-scissors.js
import { Hand } from "../game/hand";
import PlayerHand from "../components/player-hand"
import TheChoice from "../components/choice"
import { Game } from "../game/game";

import './rock-paper-scissors.scss';
import { useState } from "react";

const gameState = new Game()

let onClick = undefined

const onKey = function (event) {
    if (!onClick) { return }

    switch (event.key) {
        case '1':
            onClick(Hand.Rock)
            break
        case '2':
            onClick(Hand.Paper)
            break
        case '3':
            onClick(Hand.Scissors)
            break
        default:
            break
    }
}

document.addEventListener('keypress', onKey)

export default function RockPaperScissors() {

    // Dirty way to trigger re-rendering.
    const [gamesPlayed, setGamesPlayed] = useState(0)

    onClick = function (hand) {
        gameState.play(hand)
        setGamesPlayed(gamesPlayed + 1)
    }

    return (
        <div className="rps-content">
            <div className="result">
                <PlayerHand player={gameState.human} />
                <PlayerHand player={gameState.robot} />
            </div>

            <TheChoice onClick={onClick} />
        </div>
    )
}
